# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-05 18:28
from __future__ import unicode_literals

from django.db import migrations

def fix_python_version(apps, schema_editor):
    """Force python3 interpeter in all the projects - As they are pure docs project there is no downside in this"""
    Project = apps.get_model('projects.Project')
    Project.objects.update(python_interpreter='python3')

class Migration(migrations.Migration):

    dependencies = [
        ('docsitalia', '0015_patch_project'),
    ]

    operations = [
        migrations.RunPython(fix_python_version, migrations.RunPython.noop),
    ]
