# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-21 07:17
from __future__ import unicode_literals

from django.db import migrations, models

from readthedocs.builds.constants import LATEST
from ..migrations_schema_utils import AlterField


class Migration(migrations.Migration):

    dependencies = [
        ('docsitalia', '0016_force_python'),
    ]

    operations = [
        AlterField(
            app_label='projects',
            model_name='project',
            name='default_version',
            field=models.CharField(default=LATEST, help_text='The version of your project that / redirects to',
                                   max_length=255, verbose_name='Default version'),
        ),
    ]
