# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-18 09:21
from __future__ import unicode_literals

from django.db import migrations
from readthedocs.docsitalia.tags_vocabulary import BASE_TAGS


def sync_allowed_tags(apps, schema_editor):
    """Create missing allowed tags"""
    AllowedTag = apps.get_model('docsitalia', 'AllowedTag')
    for tag in BASE_TAGS:
        AllowedTag.objects.get_or_create(name=tag.lower(), defaults={'enabled': True})


class Migration(migrations.Migration):

    dependencies = [
        ('docsitalia', '0017_patch-project-version'),
    ]

    operations = [
        migrations.RunPython(sync_allowed_tags, migrations.RunPython.noop),
    ]
